FROM node:latest
WORKDIR /usr/local/frontend
COPY ./ /usr/local/frontend/
RUN npm install -g @angular/cli

# RUN npm run build

# Expose the port the app runs in
EXPOSE 4200

# Serve the app
# TODO: Once the app exists and is copied, run the app in the correct directory
#CMD ["npm", "start"]
