FROM python:3.10.1-slim-buster

WORKDIR /usr/src/backend
COPY . .

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get upgrade -y && apt-get install -y netcat
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/backend/requirements.txt
RUN pip install -r requirements.txt

ENTRYPOINT ["/usr/src/backend/entrypoint.sh"]
